Spotify/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('playlist_maker.urls'))
]

playlist_maker/urls.py
from django.urls import path
from . import views
app_name = 'playlist_maker'


urlpatterns =[
    path('', views.index, name = 'index'),
    path('not_found/', views.artist_not_found, name = 'artist_not_found'),
    path('playlist/', views.show_playlist, name = 'show_playlist')
]

playlist_maker/models.py
from django.db import models

# Create your models here.

playlist_maker/views.py
from django.shortcuts import render, redirect
import spotipy
import spotipy.util as util

# Create your views here.

SPOTIPY_CLIENT_ID = "1091e4ae6b354e14b4c556f1f1a6732c"
SPOTIPY_CLIENT_SECRET = "8d9f32269887450f99cd7bd106a6c3d4"
SPOTIPY_REDIRECT_URI = "http://localhost:8000/"
scope = "playlist-modify-public"
username = "ttbriyo504kilcgb12zr3tf6g"
token = util.prompt_for_user_token(username, scope, SPOTIPY_CLIENT_ID, SPOTIPY_CLIENT_SECRET, SPOTIPY_REDIRECT_URI)
sp = spotipy.Spotify(auth=token)

def index(request):
    return render(request, 'playlist_maker/index.html')

def artist_not_found(request):
    return render(request, 'playlist_maker/artist_not_found.html')


def show_playlist(request):
    if request.method == 'GET':
        desired_artist = request.GET.get("artist_to_search")
    if not desired_artist:
        return redirect('playlist_maker:index')
    desired_artist_results = sp.search(q="artist:" + desired_artist, type="artist")
    if len(desired_artist_results["artists"]["items"]) == 0:
        return redirect('playlist_maker:artist_not_found')

    desired_artist_entry = desired_artist_results["artists"]["items"][0]
    artist_name = desired_artist_entry["name"]
    artist_uri = desired_artist_entry["uri"]
    artist_image_url = desired_artist_entry["images"][0]["url"]

    playlist_name = "Inspired by " + artist_name
    sp.trace = False
    playlist = sp.user_playlist_create(username, playlist_name)
    playlist_id = playlist["id"]

    list_of_tracks = []

    artist_top_tracks = sp.artist_top_tracks(artist_uri)
    song_count = 0
    for track in artist_top_tracks["tracks"]:
        if song_count < 5:
            list_of_tracks.append(track["id"])
            song_count += 1

    add_tracks_to_playlist = sp.user_playlist_add_tracks(username, playlist_id, list_of_tracks)
    playlist_iframe_href = "https://open.spotify.com/embed?uri=spotify:user:" + username + ":playlist:" + playlist_id + "&theme=white"
    
    context = {
        'artist_name':artist_name,
        'image' :artist_image_url,
        'frame' :playlist_iframe_href 
    }

    return render(request, 'playlist_maker/playlist.html', context)

templates/playlist_maker/artist_not_found.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Playlist Maker</title>
	
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="A web app that lets you make a Spotify playlist
	full of songs by your favorite artist and artists who are similar to them.">
	<meta name="author" content="Suzen Fylke">
	
	<link rel="icon" type="image/png" href="../static/images/suzenfylke_favicon.png">	
	<link rel="stylesheet" href="../static/css/main.css" />		
	
</head>

<body>
		<!-- Wrapper -->
			<div id="wrapper" class="divided">
			


				<!-- Artist Not Found and Search -->
					<section class="banner style1 orient-right content-align-left image-position-right fullscreen onload-image-fade-in onload-content-fade-right">
						<div class="content">
							<h1>Playlist Maker</h1>
							<p class="major"><!--[-->Hmm... We can't seem to find the artist you searched for. 
							Please check the spelling and try again or search for another artist. Just enter the 
							name of an artist in the box below and click Make Playlist.<!--]--></p>
		
							<form method="GET" action="{% url 'playlist_maker:index' %}">
								<div class="field">
									<input type="text" name="artist_to_search" placeholder="Ex: Laleh" required />
								</div>										
								<ul class="actions vertical">
									<li><input type="submit" name="submit" id="submit" value="Make Playlist" class="button special"/></li>
								</ul>
							</form>	
						</div>
						
						<div class="image">
							<img src="../static/images/funky_woman_with_headphones.jpg" alt="funky woman with headphones" />
						</div>
						
					</section>
										
				

					
			</div>		
					

	
			<!-- Scripts -->
			<script src="../static/js/jquery.min.js"></script>
			<script src="../static/js/jquery.scrollex.min.js"></script>
			<script src="../static/js/jquery.scrolly.min.js"></script>
			<script src="../static/js/skel.min.js"></script>
			<script src="../static/js/util.js"></script>
			<script src="../static/js/main.js"></script>

</body>
</html>

templates/playlist_maker/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Playlist Maker</title>
	
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="A web app that lets you make a Spotify playlist
	full of songs by your favorite artist and artists who are similar to them.">
	<meta name="author" content="Suzen Fylke">
	
	<link rel="icon" type="image/png" href="../static/images/suzenfylke_favicon.png">	
	<link rel="stylesheet" href="../static/css/main.css" />		
	
</head>

<body>
		<!-- Wrapper -->
			<div id="wrapper" class="divided">

				<!-- Intro and Search -->
					<section class="banner style1 orient-right content-align-left image-position-right fullscreen onload-image-fade-in onload-content-fade-left">
						<div class="content">
							<h1>Playlist Maker</h1>
							<p class="major"><!--[-->Welcome to Playlist Maker, a web app that lets you make a Spotify playlist 
							full of songs by your favorite artist and artists who are similar to them. Just enter the 
							name of an artist in the box below and click Make Playlist.<!--]--></p>
		
							<form method="GET" action="{% url 'playlist_maker:show_playlist' %}" > 
								<div class="field">
									<input type="text" name="artist_to_search" placeholder="Ex: Davido" required />
								</div>										
								<ul class="actions vertical">
									<li><input type="submit" name="submit" id="submit" value="Make Playlist" class="button special"/></li>
								</ul>
							</form>	
						</div>
	
						<div class="image">
							<img src="../static/images/funky_woman_with_headphones.jpg" alt="funky woman with headphones" />
						</div>
						
					</section>
		
			</div>				

	
			<!-- Scripts -->
			<script src="../static/js/jquery.min.js"></script>
			<script src="../static/js/jquery.scrollex.min.js"></script>
			<script src="../static/js/jquery.scrolly.min.js"></script>
			<script src="../static/js/skel.min.js"></script>
			<script src="../static/js/util.js"></script>
			<script src="../static/js/main.js"></script>

</body>
</html>

templates/playlist_maker/playlist.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Playlist Maker</title>
	
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="A web app that lets you make a Spotify playlist
	full of songs by your favorite artist and artists who are similar to them.">
	<meta name="author" content="Suzen Fylke">
	
	<link rel="icon" type="image/png" href="../static/images/suzenfylke_favicon.png">	
	<link rel="stylesheet" href="../static/css/main.css" />		
	
</head>

<body>
		<!-- Wrapper -->
			<div id="wrapper" class="divided">
			
				<!-- Your Playlist Results -->
					<section class="banner style1 orient-left content-align-left image-position-center fullscreen onload-image-fade-in onload-content-fade-right">
						<div class="content">
							<h2>Here's Your Playlist</h2>
							<p>Your playlist is full of popular songs by {{ artist_name }}. Enjoy! 
							<br /><a href="{% url 'playlist_maker:index' %}">Click here to make another playlist.</a></p>
							<!--Change player them by pasting or removing &theme=white at the end of playlist url. -->
							<iframe src="{{ frame }}" width="100%" height="300" frameborder="0" allowtransparency="true"></iframe>
						</div>
						<div class="image">
							<img src="{{ image }}" alt="image of artist you searched for" />
						</div>
					</section>	
										
			</div>		
					

	
			<!-- Scripts -->
			<script src="../static/js/jquery.min.js"></script>
			<script src="../static/js/jquery.scrollex.min.js"></script>
			<script src="../static/js/jquery.scrolly.min.js"></script>
			<script src="../static/js/skel.min.js"></script>
			<script src="../static/js/util.js"></script>
			<script src="../static/js/main.js"></script>

</body>
</html>